name: golangci-lint
on:
  pull_request:
jobs:
  golangci:
    name: lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-go@fac708d6674e30b6ba41289acaab6d4b75aa0753
        with:
          go-version: '1.20.0'
      - uses: actions/checkout@f43a0e5ff2bd294095638e18286ca9a3d1956744
      - name: golangci-lint
        uses: golangci/golangci-lint-action@v3.6.0
        with:
          version: v1.52.2
